### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [vnebelunka/inm-prac#2]
1) Умножение на матрицы вращения слева и справа лучше делать по-разному: при хранении матриц по строкам (столбцам) вращения строк (столбцов) можно применять сразу при вычислении ко всей строке (столбцу), а вот вращение столбцов (строк) лучше откладывать до того, как будут вычислены  вращения, обнуляющие необходимые элементы в текущем столбце (строке), а далее применять все эти вращения к остальным столбцам построчно (постолбцово).

2) Нет BLAS / LAPACK.

**Comment by vnebelunka** [comment]
1. Реализации вращения на строчки и столбцы разные. Например, в случае кода на с++ синусы и косинусы собираются в массив во время прохода по строкам, по которому потом проводятся одновременные вращения по столбцам
2. Добавлены реализации BLAS / LAPACK на C / Fortran
